import {
  Category,
  PaymentMethod,
  Profile,
  SiftBackupData,
  Subscription,
  BackupValidationResult,
} from '../types';

/**
 * Serializes all user-owned records into a versioned, portable Sift JSON backup structure
 */
export function generateFullBackupJson(params: {
  userEmail?: string;
  profile?: Profile | null;
  subscriptions: Subscription[];
  categories: Category[];
  paymentMethods?: PaymentMethod[];
}): SiftBackupData {
  const { userEmail, profile, subscriptions, categories, paymentMethods = [] } = params;

  // Clean subscriptions to remove internal DB autogenerated IDs/timestamps for clean portability
  const sanitizedSubscriptions = subscriptions.map((s) => ({
    name: s.name,
    description: s.description || undefined,
    amount: s.amount,
    currency: s.currency,
    billing_cycle: s.billing_cycle,
    custom_interval_days: s.custom_interval_days || undefined,
    status: s.status,
    category_slug: s.category?.slug || undefined,
    start_date: s.start_date,
    next_renewal_date: s.next_renewal_date,
    is_trial: s.is_trial,
    trial_end_date: s.trial_end_date || undefined,
    reminder_offsets: s.reminder_offsets || [7, 3, 1],
    value_rating: s.value_rating,
    cancel_url: s.cancel_url || undefined,
    notes: s.notes || undefined,
    monthly_amount: s.monthly_amount,
  }));

  return {
    version: '1.0',
    app: 'Sift',
    exported_at: new Date().toISOString(),
    user_email: userEmail || profile?.email || 'unknown@sift.studio',
    profile: {
      currency_preference: profile?.currency_preference || 'USD',
      theme_preference: profile?.theme_preference || 'paper-ledger',
      default_reminder_days: profile?.default_reminder_days || [7, 3, 1],
      notifications_enabled: profile?.notifications_enabled !== false,
      notify_renewals: profile?.notify_renewals !== false,
      notify_trials: profile?.notify_trials !== false,
    },
    subscriptions: sanitizedSubscriptions as any,
    categories: categories.map((c) => ({
      id: c.id,
      name: c.name,
      slug: c.slug,
      color: c.color,
      icon: c.icon,
      created_at: c.created_at,
    })),
    payment_methods: paymentMethods.map((p) => ({
      id: p.id,
      user_id: p.user_id,
      name: p.name,
      type: p.type,
      last4: p.last4,
      color: p.color,
      is_default: p.is_default,
      created_at: p.created_at,
    })),
  };
}

/**
 * Generates human-readable CSV representation of all subscriptions
 */
export function generateSubscriptionsCsv(subscriptions: Subscription[]): string {
  const headers = [
    'Name',
    'Amount',
    'Currency',
    'Billing Cycle',
    'Status',
    'Category',
    'Value Rating',
    'Next Renewal Date',
    'Is Trial',
    'Trial End Date',
    'Monthly Run-Rate',
    'Cancellation URL',
    'Notes',
  ];

  const rows = subscriptions.map((s) => [
    `"${(s.name || '').replace(/"/g, '""')}"`,
    s.amount,
    s.currency,
    s.billing_cycle,
    s.status,
    `"${(s.category?.name || 'General').replace(/"/g, '""')}"`,
    s.value_rating,
    s.next_renewal_date,
    s.is_trial ? 'Yes' : 'No',
    s.trial_end_date || '',
    s.monthly_amount,
    `"${(s.cancel_url || '').replace(/"/g, '""')}"`,
    `"${(s.notes || '').replace(/"/g, '""')}"`,
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

/**
 * Generates human-readable README manifest for backup archives
 */
export function generateBackupReadme(backup: SiftBackupData): string {
  return `================================================================================
SIFT DATA BACKUP MANIFEST
================================================================================
Application: Sift (Personal Recurring Spend Workspace)
Version: ${backup.version}
Exported At: ${backup.exported_at}
Account: ${backup.user_email}

CONTENTS SUMMARY:
- Total Subscriptions: ${backup.subscriptions.length}
- Categories: ${backup.categories.length}
- Primary Currency: ${backup.profile.currency_preference || 'USD'}
- Theme: ${backup.profile.theme_preference || 'Paper Ledger'}

FILE DESCRIPTIONS:
1. sift-backup-${backup.exported_at.split('T')[0]}.json
   Complete machine-readable JSON structure. Contains full subscription records,
   category tags, reminder preferences, and currency settings. Can be used to restore
   your Sift account at any time in Settings > Restore Backup.

2. sift-subscriptions-${backup.exported_at.split('T')[0]}.csv
   Open tabular spreadsheet format suitable for Microsoft Excel, Apple Numbers,
   or Google Sheets.

PRIVACY & OWNERSHIP:
This export contains only user-owned data created within your personal Sift workspace.
No passwords, authentication tokens, or internal credentials are included.
================================================================================`;
}

/**
 * Validates an uploaded JSON file before restoring
 */
export function validateBackupJson(rawJsonText: string): BackupValidationResult {
  try {
    const data = JSON.parse(rawJsonText);

    if (!data || typeof data !== 'object') {
      return { valid: false, error: 'Invalid JSON file structure.' };
    }

    if (data.app !== 'Sift' && !Array.isArray(data.subscriptions)) {
      return {
        valid: false,
        error: 'File does not appear to be a recognized Sift backup format.',
      };
    }

    if (!Array.isArray(data.subscriptions)) {
      return {
        valid: false,
        error: 'Backup file is missing the subscriptions array.',
      };
    }

    // Validate subscriptions schema
    for (let i = 0; i < data.subscriptions.length; i++) {
      const sub = data.subscriptions[i];
      if (!sub.name || typeof sub.amount !== 'number') {
        return {
          valid: false,
          error: `Subscription at index ${i} is missing a required name or numeric amount.`,
        };
      }
    }

    return {
      valid: true,
      data: data as SiftBackupData,
      counts: {
        subscriptions: data.subscriptions.length,
        categories: Array.isArray(data.categories) ? data.categories.length : 0,
        paymentMethods: Array.isArray(data.payment_methods) ? data.payment_methods.length : 0,
      },
    };
  } catch (err: any) {
    return { valid: false, error: `JSON parse error: ${err.message}` };
  }
}

/**
 * Triggers a client-side file download in the user's browser
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
