import {
  Category,
  PaymentMethod,
  Profile,
  SiftBackupData,
  Subscription,
  BackupValidationResult,
} from '../types';

/**
 * Serializes all user-owned records into a versioned, portable Sift JSON backup structure
 */
export function generateFullBackupJson(params: {
  userEmail?: string;
  profile?: Profile | null;
  subscriptions: Subscription[];
  categories: Category[];
  paymentMethods?: PaymentMethod[];
}): SiftBackupData {
  const { userEmail, profile, subscriptions, categories, paymentMethods = [] } = params;

  // Clean subscriptions to remove internal DB autogenerated IDs/timestamps for clean portability.
  // We capture category_slug as a portable snapshot to reliably restore subscription-to-category associations
  // across environments where internal category UUIDs differ or categories have been renamed/aliased.
  const sanitizedSubscriptions = subscriptions.map((s) => {
    const resolvedCategorySlug =
      s.category?.slug ||
      (s.category_id ? categories.find((c) => c.id === s.category_id)?.slug : undefined) ||
      undefined;

    return {
      name: s.name,
      description: s.description || undefined,
      amount: s.amount,
      currency: s.currency,
      billing_cycle: s.billing_cycle,
      custom_interval_days: s.custom_interval_days || undefined,
      status: s.status,
      category_slug: resolvedCategorySlug,
      start_date: s.start_date,
      next_renewal_date: s.next_renewal_date,
      is_trial: s.is_trial,
      trial_end_date: s.trial_end_date || undefined,
      reminder_offsets: s.reminder_offsets || [7, 3, 1],
      value_rating: s.value_rating,
      cancel_url: s.cancel_url || undefined,
      notes: s.notes || undefined,
      monthly_amount: s.monthly_amount,
    };
  });

  return {
    version: '1.0',
    app: 'Sweep',
    exported_at: new Date().toISOString(),
    user_email: userEmail || profile?.email || 'unknown@sweep.app',
    profile: {
      currency_preference: profile?.currency_preference || 'USD',
      theme_preference: profile?.theme_preference || 'paper-ledger',
      default_reminder_days: profile?.default_reminder_days || [7, 3, 1],
      annual_benchmark_percent: profile?.annual_benchmark_percent ?? 16.7,
      category_annual_benchmarks: profile?.category_annual_benchmarks ?? {},
      notifications_enabled: profile?.notifications_enabled !== false,
      notify_renewals: profile?.notify_renewals !== false,
      notify_trials: profile?.notify_trials !== false,
    },
    subscriptions: sanitizedSubscriptions as any,
    categories: categories.map((c) => ({
      id: c.id,
      user_id: c.user_id ?? null,
      name: c.name,
      slug: c.slug,
      slug_aliases: c.slug_aliases || [],
      color: c.color,
      icon: c.icon,
      created_at: c.created_at,
    })),
    payment_methods: paymentMethods.map((p) => ({
      id: p.id,
      user_id: p.user_id,
      name: p.name,
      type: p.type,
      last4: p.last4,
      color: p.color,
      is_default: p.is_default,
      created_at: p.created_at,
    })),
  };
}

/**
 * Generates human-readable CSV representation of all subscriptions
 */
export function generateSubscriptionsCsv(subscriptions: Subscription[]): string {
  const headers = [
    'Name',
    'Amount',
    'Currency',
    'Billing Cycle',
    'Status',
    'Category',
    'Value Rating',
    'Next Renewal Date',
    'Is Trial',
    'Trial End Date',
    'Monthly Run-Rate',
    'Cancellation URL',
    'Notes',
  ];

  const rows = subscriptions.map((s) => [
    `"${(s.name || '').replace(/"/g, '""')}"`,
    s.amount,
    s.currency,
    s.billing_cycle,
    s.status,
    `"${(s.category?.name || 'General').replace(/"/g, '""')}"`,
    s.value_rating,
    s.next_renewal_date,
    s.is_trial ? 'Yes' : 'No',
    s.trial_end_date || '',
    s.monthly_amount,
    `"${(s.cancel_url || '').replace(/"/g, '""')}"`,
    `"${(s.notes || '').replace(/"/g, '""')}"`,
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

/**
 * Generates human-readable README manifest for backup archives
 */
export function generateBackupReadme(backup: SiftBackupData): string {
  return `================================================================================
SWEEP DATA BACKUP MANIFEST
================================================================================
Application: Sweep (Your recurring life, in one clear view)
Version: ${backup.version}
Exported At: ${backup.exported_at}
Account: ${backup.user_email}

CONTENTS SUMMARY:
- Total Subscriptions: ${backup.subscriptions.length}
- Categories: ${backup.categories.length}
- Primary Currency: ${backup.profile.currency_preference || 'USD'}
- Theme: ${backup.profile.theme_preference || 'Warm Ledger'}
- Annual Discount Benchmark: ${backup.profile.annual_benchmark_percent ?? 16.7}% (${Object.keys(backup.profile.category_annual_benchmarks || {}).length} category override(s))

FILE DESCRIPTIONS:
1. sweep-backup-${backup.exported_at.split('T')[0]}.json
   Complete machine-readable JSON structure. Contains full subscription records,
   category tags, reminder preferences, and currency settings. Can be used to restore
   your Sweep account at any time in Settings > Restore Backup.

2. sweep-subscriptions-${backup.exported_at.split('T')[0]}.csv
   Open tabular spreadsheet format suitable for Microsoft Excel, Apple Numbers,
   or Google Sheets.

PRIVACY & OWNERSHIP:
This export contains only user-owned data created within your personal Sweep workspace.
No passwords, authentication tokens, or internal credentials are included.
================================================================================`;
}

/**
 * Validates an uploaded JSON file before restoring
 */
export function validateBackupJson(rawJsonText: string): BackupValidationResult {
  try {
    const data = JSON.parse(rawJsonText);

    if (!data || typeof data !== 'object') {
      return { valid: false, error: 'Invalid JSON file structure.' };
    }

    if (data.app !== 'Sweep' && data.app !== 'Sift' && !Array.isArray(data.subscriptions)) {
      return {
        valid: false,
        error: 'File does not appear to be a recognized Sweep or Sift backup format.',
      };
    }

    if (!Array.isArray(data.subscriptions)) {
      return {
        valid: false,
        error: 'Backup file is missing the subscriptions array.',
      };
    }

    // Validate subscriptions schema
    for (let i = 0; i < data.subscriptions.length; i++) {
      const sub = data.subscriptions[i];
      if (!sub.name || typeof sub.amount !== 'number') {
        return {
          valid: false,
          error: `Subscription at index ${i} is missing a required name or numeric amount.`,
        };
      }
    }

    return {
      valid: true,
      data: data as SiftBackupData,
      counts: {
        subscriptions: data.subscriptions.length,
        categories: Array.isArray(data.categories) ? data.categories.length : 0,
        paymentMethods: Array.isArray(data.payment_methods) ? data.payment_methods.length : 0,
      },
    };
  } catch (err: any) {
    return { valid: false, error: `JSON parse error: ${err.message}` };
  }
}

/**
 * Triggers a client-side file download in the user's browser
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export interface CategoryBenchmarkCollision {
  sourceKey: string;
  sourceSlug: string;
  sourceName?: string;
  configuredBenchmark: number;
  conflictingCategories: { id: string; name: string; slug: string }[];
}

export interface CategoryBenchmarkUnmatched {
  sourceKey: string;
  sourceSlug?: string;
  sourceName?: string;
  configuredBenchmark: number;
}

export interface CategoryBenchmarkRestoreReport {
  remappedBenchmarks: Record<string, number>;
  matchedByUuid: number;
  matchedBySlug: number;
  matchedByAlias: number;
  skippedAmbiguous: number;
  skippedMissing: number;
  collisions: CategoryBenchmarkCollision[];
  unmatched: CategoryBenchmarkUnmatched[];
}

/**
 * Maps backup category benchmark overrides to the active workspace categories.
 * Primary: Match by exact Category UUID.
 * Fallback Tier 1: Match by Category Primary Slug when UUID differs across database instances.
 * Fallback Tier 2: Match by Category Historical Slug Aliases (preserves renamed categories across environments).
 * Safety: Ambiguous matches (multiple categories with identical slugs or aliases) are skipped without guessing.
 */
export function remapCategoryBenchmarkOverrides(
  backupBenchmarks: Record<string, number> = {},
  backupCategories: Category[] = [],
  currentCategories: Category[] = []
): CategoryBenchmarkRestoreReport {
  const remappedBenchmarks: Record<string, number> = {};
  const collisions: CategoryBenchmarkCollision[] = [];
  const unmatched: CategoryBenchmarkUnmatched[] = [];
  let matchedByUuid = 0;
  let matchedBySlug = 0;
  let matchedByAlias = 0;
  let skippedAmbiguous = 0;
  let skippedMissing = 0;

  if (!backupBenchmarks || typeof backupBenchmarks !== 'object') {
    return {
      remappedBenchmarks,
      matchedByUuid,
      matchedBySlug,
      matchedByAlias,
      skippedAmbiguous,
      skippedMissing,
      collisions,
      unmatched,
    };
  }

  for (const [key, value] of Object.entries(backupBenchmarks)) {
    if (typeof value !== 'number' || isNaN(value)) continue;

    // 1. Primary path: Exact UUID match in active categories
    const exactUuidMatch = currentCategories.find((c) => c.id === key);
    if (exactUuidMatch) {
      remappedBenchmarks[exactUuidMatch.id] = value;
      matchedByUuid++;
      continue;
    }

    // 2. Fallback path: Find category slug from backup categories metadata or direct slug key
    let sourceSlug: string | undefined;
    let sourceName: string | undefined;
    const backupCat = backupCategories.find((c) => c.id === key);
    if (backupCat) {
      sourceName = backupCat.name;
      if (backupCat.slug) {
        sourceSlug = backupCat.slug.trim().toLowerCase();
      }
    } else if (
      currentCategories.some((c) => c.slug?.trim().toLowerCase() === key.trim().toLowerCase())
    ) {
      sourceSlug = key.trim().toLowerCase();
    }

    if (!sourceSlug) {
      skippedMissing++;
      unmatched.push({
        sourceKey: key,
        sourceName,
        configuredBenchmark: value,
      });
      continue;
    }

    // Tier 1 fallback: Search for matching categories by primary slug in active categories
    const slugMatches = currentCategories.filter(
      (c) => c.slug && c.slug.trim().toLowerCase() === sourceSlug
    );

    if (slugMatches.length === 1) {
      // Unique deterministic primary slug match
      remappedBenchmarks[slugMatches[0].id] = value;
      matchedBySlug++;
      continue;
    } else if (slugMatches.length > 1) {
      // Ambiguous primary slug collision - safe skip without guessing
      skippedAmbiguous++;
      collisions.push({
        sourceKey: key,
        sourceSlug,
        sourceName: sourceName || sourceSlug,
        configuredBenchmark: value,
        conflictingCategories: slugMatches.map((c) => ({
          id: c.id,
          name: c.name,
          slug: c.slug,
        })),
      });
      continue;
    }

    // Tier 2 fallback: Search for matching categories by historical slug aliases
    const aliasMatches = currentCategories.filter((c) =>
      c.slug_aliases?.some((alias) => alias.trim().toLowerCase() === sourceSlug)
    );

    if (aliasMatches.length === 1) {
      // Unique deterministic alias match for renamed categories
      remappedBenchmarks[aliasMatches[0].id] = value;
      matchedBySlug++;
      matchedByAlias++;
    } else if (aliasMatches.length > 1) {
      // Ambiguous alias collision across multiple categories
      skippedAmbiguous++;
      collisions.push({
        sourceKey: key,
        sourceSlug,
        sourceName: sourceName || sourceSlug,
        configuredBenchmark: value,
        conflictingCategories: aliasMatches.map((c) => ({
          id: c.id,
          name: c.name,
          slug: c.slug,
        })),
      });
    } else {
      // No active category matching this primary slug or historical aliases
      skippedMissing++;
      unmatched.push({
        sourceKey: key,
        sourceSlug,
        sourceName: sourceName || sourceSlug,
        configuredBenchmark: value,
      });
    }
  }

  return {
    remappedBenchmarks,
    matchedByUuid,
    matchedBySlug,
    matchedByAlias,
    skippedAmbiguous,
    skippedMissing,
    collisions,
    unmatched,
  };
}

/**
 * Calculates string similarity score between 0 and 1 using bigram Jaccard/Dice coefficient
 */
export function calculateStringSimilarity(str1: string, str2: string): number {
  const s1 = str1.toLowerCase().trim().replace(/[^a-z0-9]/g, '');
  const s2 = str2.toLowerCase().trim().replace(/[^a-z0-9]/g, '');

  if (s1 === s2) return 1.0;
  if (!s1 || !s2) return 0.0;
  if (s1.includes(s2) || s2.includes(s1)) return 0.85;

  const getBigrams = (str: string) => {
    const bigrams = new Set<string>();
    for (let i = 0; i < str.length - 1; i++) {
      bigrams.add(str.slice(i, i + 2));
    }
    return bigrams;
  };

  const b1 = getBigrams(s1);
  const b2 = getBigrams(s2);

  if (b1.size === 0 || b2.size === 0) return 0.0;

  let intersection = 0;
  for (const item of b1) {
    if (b2.has(item)) intersection++;
  }

  return (2.0 * intersection) / (b1.size + b2.size);
}

/**
 * Ranks candidate destination categories for an unmatched item based on name/slug similarity.
 * Note: Suggestions are advisory ONLY for manual review and are NEVER auto-applied silently.
 */
export function findCategorySuggestion(
  sourceNameOrSlug: string,
  categories: Category[],
  threshold: number = 0.55
): { category: Category; similarity: number } | null {
  if (!sourceNameOrSlug || categories.length === 0) return null;

  let bestMatch: { category: Category; similarity: number } | null = null;

  for (const cat of categories) {
    const nameScore = calculateStringSimilarity(sourceNameOrSlug, cat.name);
    const slugScore = cat.slug ? calculateStringSimilarity(sourceNameOrSlug, cat.slug) : 0;
    const score = Math.max(nameScore, slugScore);

    if (score >= threshold && (!bestMatch || score > bestMatch.similarity)) {
      bestMatch = { category: cat, similarity: score };
    }
  }

  return bestMatch;
}

/**
 * Calm, theme-safe palette for imported/created categories lacking explicit color metadata.
 * Designed for visual clarity and contrast in both Paper Ledger (light) and Night Shelf (dark) themes.
 */
export const DEFAULT_CATEGORY_PRESET_COLORS = [
  '#527243', // Moss Green
  '#5B294A', // Rich Ink Plum
  '#A65A24', // Toasted Amber
  '#4f46e5', // Deep Indigo
  '#8b5cf6', // Muted Orchid
  '#A63F3A', // Brick Red
  '#64748b', // Warm Slate
  '#d97706', // Ochre
] as const;

/**
 * Deterministically resolves a preset category color.
 * If importedColor is provided and non-empty, it is preserved.
 * Otherwise, assigns a deterministic preset color based on item index or name/slug hash.
 */
export function resolveCategoryDefaultColor(
  importedColor?: string | null,
  nameOrSlug?: string | null,
  index?: number
): string {
  if (importedColor && importedColor.trim()) {
    return importedColor.trim();
  }

  if (index !== undefined && index >= 0) {
    return DEFAULT_CATEGORY_PRESET_COLORS[index % DEFAULT_CATEGORY_PRESET_COLORS.length];
  }

  if (nameOrSlug && nameOrSlug.trim()) {
    let hash = 0;
    const str = nameOrSlug.trim().toLowerCase();
    for (let i = 0; i < str.length; i++) {
      hash = (hash << 5) - hash + str.charCodeAt(i);
      hash |= 0;
    }
    const colorIndex = Math.abs(hash) % DEFAULT_CATEGORY_PRESET_COLORS.length;
    return DEFAULT_CATEGORY_PRESET_COLORS[colorIndex];
  }

  return DEFAULT_CATEGORY_PRESET_COLORS[0];
}
