export interface PopularService {
  name: string;
  defaultAmount?: number;
  currency?: string;
  billingCycle?: 'monthly' | 'yearly';
  categorySlug?: string;
  cancelUrl?: string;
  description?: string;
}

export const POPULAR_SERVICES: PopularService[] = [
  {
    name: 'Cursor Pro',
    defaultAmount: 20,
    billingCycle: 'monthly',
    categorySlug: 'software-dev',
    cancelUrl: 'https://cursor.com/settings',
    description: 'AI code editor',
  },
  {
    name: 'GitHub Copilot',
    defaultAmount: 10,
    billingCycle: 'monthly',
    categorySlug: 'software-dev',
    cancelUrl: 'https://github.com/settings/billing',
    description: 'AI pair programmer',
  },
  {
    name: 'ChatGPT Plus',
    defaultAmount: 20,
    billingCycle: 'monthly',
    categorySlug: 'software-dev',
    cancelUrl: 'https://chatgpt.com/#settings',
    description: 'OpenAI subscription',
  },
  {
    name: 'Claude Pro',
    defaultAmount: 20,
    billingCycle: 'monthly',
    categorySlug: 'software-dev',
    cancelUrl: 'https://claude.ai/settings/billing',
    description: 'Anthropic AI assistant',
  },
  {
    name: 'Spotify Premium',
    defaultAmount: 11.99,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://www.spotify.com/account/overview/',
    description: 'Music streaming',
  },
  {
    name: 'Apple Music',
    defaultAmount: 10.99,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://music.apple.com',
    description: 'Music streaming',
  },
  {
    name: 'YouTube Premium',
    defaultAmount: 13.99,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    description: 'Ad-free video & music',
  },
  {
    name: 'Netflix Standard',
    defaultAmount: 15.49,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://www.netflix.com/youraccount',
    description: 'Movie & TV streaming',
  },
  {
    name: 'Disney+',
    defaultAmount: 13.99,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://www.disneyplus.com/account',
    description: 'Streaming service',
  },
  {
    name: 'Amazon Prime',
    defaultAmount: 14.99,
    billingCycle: 'monthly',
    categorySlug: 'utilities-sync',
    cancelUrl: 'https://www.amazon.com/mc/manage',
    description: 'Prime membership',
  },
  {
    name: 'iCloud+ 50GB',
    defaultAmount: 0.99,
    billingCycle: 'monthly',
    categorySlug: 'infra-cloud',
    cancelUrl: 'https://appleid.apple.com',
    description: 'Apple cloud storage',
  },
  {
    name: 'iCloud+ 200GB',
    defaultAmount: 2.99,
    billingCycle: 'monthly',
    categorySlug: 'infra-cloud',
    cancelUrl: 'https://appleid.apple.com',
    description: 'Apple cloud storage',
  },
  {
    name: 'Google One 100GB',
    defaultAmount: 1.99,
    billingCycle: 'monthly',
    categorySlug: 'infra-cloud',
    cancelUrl: 'https://one.google.com/settings',
    description: 'Google cloud storage',
  },
  {
    name: 'Google One 2TB',
    defaultAmount: 9.99,
    billingCycle: 'monthly',
    categorySlug: 'infra-cloud',
    cancelUrl: 'https://one.google.com/settings',
    description: 'Google cloud storage',
  },
  {
    name: 'Dropbox Plus',
    defaultAmount: 11.99,
    billingCycle: 'monthly',
    categorySlug: 'infra-cloud',
    cancelUrl: 'https://www.dropbox.com/account/plan',
    description: 'Cloud file sync',
  },
  {
    name: '1Password Individual',
    defaultAmount: 2.99,
    billingCycle: 'monthly',
    categorySlug: 'utilities-sync',
    cancelUrl: 'https://my.1password.com/profile',
    description: 'Password manager',
  },
  {
    name: 'Bitwarden Premium',
    defaultAmount: 10.0,
    billingCycle: 'yearly',
    categorySlug: 'utilities-sync',
    cancelUrl: 'https://vault.bitwarden.com/#/settings/subscription',
    description: 'Password manager',
  },
  {
    name: 'Fastmail Standard',
    defaultAmount: 5.0,
    billingCycle: 'monthly',
    categorySlug: 'utilities-sync',
    cancelUrl: 'https://www.fastmail.com/settings/billing',
    description: 'Private email',
  },
  {
    name: 'Proton Unlimited',
    defaultAmount: 9.99,
    billingCycle: 'monthly',
    categorySlug: 'utilities-sync',
    cancelUrl: 'https://account.proton.me/u/0/mail/subscription',
    description: 'Encrypted privacy suite',
  },
  {
    name: 'Notion Plus',
    defaultAmount: 10.0,
    billingCycle: 'monthly',
    categorySlug: 'productivity',
    cancelUrl: 'https://www.notion.so/settings',
    description: 'Workspace & notes',
  },
  {
    name: 'Figma Professional',
    defaultAmount: 15.0,
    billingCycle: 'monthly',
    categorySlug: 'software-dev',
    cancelUrl: 'https://www.figma.com/settings',
    description: 'Interface design tool',
  },
  {
    name: 'Vercel Pro',
    defaultAmount: 20.0,
    billingCycle: 'monthly',
    categorySlug: 'infra-cloud',
    cancelUrl: 'https://vercel.com/dashboard/billing',
    description: 'Frontend cloud platform',
  },
  {
    name: 'Linear Standard',
    defaultAmount: 10.0,
    billingCycle: 'monthly',
    categorySlug: 'productivity',
    cancelUrl: 'https://linear.app/settings/billing',
    description: 'Issue & project tracking',
  },
  {
    name: 'Midjourney Basic',
    defaultAmount: 10.0,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://www.midjourney.com/account',
    description: 'Generative AI imagery',
  },
  {
    name: 'Superhuman',
    defaultAmount: 30.0,
    billingCycle: 'monthly',
    categorySlug: 'productivity',
    cancelUrl: 'https://mail.superhuman.com',
    description: 'Fast email client',
  },
  {
    name: 'Gym Membership',
    defaultAmount: 50.0,
    billingCycle: 'monthly',
    categorySlug: 'health-routine',
    description: 'Health & fitness',
  },
  {
    name: 'Headspace',
    defaultAmount: 12.99,
    billingCycle: 'monthly',
    categorySlug: 'health-routine',
    cancelUrl: 'https://www.headspace.com/subscription',
    description: 'Mindfulness & meditation',
  },
  {
    name: 'New York Times',
    defaultAmount: 4.0,
    billingCycle: 'monthly',
    categorySlug: 'media-reading',
    cancelUrl: 'https://www.nytimes.com/subscription',
    description: 'News & journalism',
  },
];
